# Generated by Django 3.1.7 on 2021-03-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210304_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='Not LoggedIN', max_length=200, null=True),
        ),
    ]
