# Generated by Django 3.1.5 on 2021-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='hastag1',
            field=models.CharField(default='Fresh', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='hastag2',
            field=models.CharField(default='Trendy', max_length=20),
        ),
    ]
