# Generated by Django 3.1.5 on 2021-01-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210129_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('review', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.item')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
