# Generated by Django 3.1.5 on 2021-01-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='body',
        ),
    ]
