# Generated by Django 3.1.7 on 2021-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210304_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='one_click_purchasing',
            field=models.BooleanField(default=False),
        ),
    ]
